config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show]
  resources :teams, only: [:index, :show]
  resources :stocks, only: [:index, :show]
  # get 'teams/index'
  # get 'teams/show'
  # get 'stocks/index'
  # get 'stocks/show'
  # get 'users/index'
  # get 'users/show'
  root 'users#index'
  
  resources :withdraws, only: [:new, :create]
  resources :deposits, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/wallet_concern.rb
module WalletConcern
  include ActiveSupport::Concern

  def create_wallet
    wallet.create
  end
end

app/models/deposit.rb
class Deposit < Transaction; end

app/models/stock.rb
class Stock < ApplicationRecord
  extend WalletConcern

  has_one :wallet, as: :walletable
  belongs_to :user

  after_create :create_wallet
end

app/models/team.rb
class Team < ApplicationRecord
  extend WalletConcern
  has_one :wallet, as: :walletable
  
  has_and_belongs_to_many :users

  after_create :create_wallet
end

app/models/transaction.rb
class TransactionValidator < ActiveModel::Validator
  def validate(record)
    if record.to_wallet_id.nil?
      record.errors[:to_wallet_id] << 'Destination wallet needs to be valid'
    end

    if record.from_wallet_id.nil?
      record.errors[:from_wallet_id] << 'Source wallet needs to be valid'
    end

    if record.to_wallet_id == record.from_wallet_id
      record.errors[:to_wallet_id] << 'Destination wallet needs to be different from source wallet'
    end
  end
end

class Transaction < ApplicationRecord
  include ActiveModel::Validations
  include AASM

  validates_with TransactionValidator

  enum aasm_state: {
    initiated: 0,
    accepted: 1,
    rejected: 2,
    locked_funds: 3,
    succeed: 4,
    failed: 5
  }

  belongs_to :from_wallet, class_name: "Wallet"
  belongs_to :to_wallet, class_name: "Wallet"

  before_validation :generate_attributes, on: :create

  def self.types
    %w(Withdraw Deposit)
  end

  scope :deposits, -> { where(type: 'Deposit') }
  scope :Withdraws, -> { where(type: 'Withdraw')}

  scope :succeed, -> { where(aasm_state: 'succeed') }

  aasm enum: true, whiny_transactions: false do
    state :initiated, initial: true
    state :accepted
    state :rejected
    state :locked_funds
    state :succeed
    state :failed
  
    event :accept do
      transitions from: :initiated, to: :accepted
    end

    event :reject do
      transitions from: :initiated, to: :rejected
    end

    event :lock_funds do
      transitions from: :accepted, to: :locked_funds
      after { from_wallet.lock!.lock_funds(amount)}
    end

    event :success do
      transitions from: :locked_funds, to: :succeed
      after { from_wallet.lock!.unlock_funds(amount)}
    end

    event :fail do
      transitions from: :locked_funds, to: :failed
      after { from_wallet.lock!.unlock_funds(amount)}
    end
  end

  def order(from_wallet, to_wallet, amount)
    Transaction.create(amount: amount, from_wallet: from_wallet, to_wallet: to_wallet)
  end

  private

  def generate_attributes
    self.aasm_state = 'initiated'
    set_tx_no
  end

  def set_tx_no
    loop do
      self.tx_no = SecureRandom.hex[0..7].upcase
      break unless Transaction.exists?(tx_no: self.tx_no)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend WalletConcern
  has_one :wallet, as: :walletable

  has_and_belongs_to_many :teams
  has_many :stocks

  after_create :create_wallet
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :walletable, polymorphic: true

  has_many :credits, class_name: "Transaction", foreign_key: 'to_wallet_id'
  has_many :debits, class_name: "Transaction", foreign_key: 'from_wallet_id'

  delegate :deposits, :withdraws, to: :transactions

  def balance
    sum.to_f - locked.to_f
  end

  def sum
    deposits = Transaction.succeed.where(to_wallet: self).sum(:amount).to_f
    withdraws = Transaction.succeed.where(from_wallet: self).sum(:amount).to_f
    cash_deposit.to_f + deposits - withdraws
  end

  ZERO = 0.to_d

  before_validation :generate_attributes, on: :create
  validates_numericality_of :balance, :locked, greater_than_or_equal_to: ZERO

  def lock_funds(amount)
    (amount <= ZERO or amount > self.balance) and raise WalletError, I18n.t("activerecord.errors.messages.cannot_lock_funds", amount: amount)
    change_locked amount
  end

  def unlock_funds(amount, reason: nil, ref: nil)
    (amount <= ZERO or amount > self.locked) and raise WalletError, I18n.t("activerecord.errors.messages.cannot_unlock_funds", amount: amount)
    change_locked -amount
  end

  def change_locked(delta_l)
    self.with_lock do
      self.update(locked: self.locked + delta_l)
    end
    self
  end

  class WalletError < RuntimeError; end

  private

  def generate_attributes
    self.locked = ZERO
    self.cash_deposit = ZERO
  end
end

app/models/withdraw.rb
class Withdraw < Transaction; end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController

  def new
    @type = params[:type]
    id = params[:id]
    if @type == "user"
      @user = User.find(id)
      @wallet = @user.wallet
    elsif @type == "team"
      @team = Team.find(id)
      @wallet = @team.wallet
    else
      @stock = Stock.find(id)
      @wallet = @stock.wallet
    end
    @wallets = Wallet.all
    @deposit = Deposit.new
  end

  def create
    deposit = Deposit.new(deposit_params)
    if deposit.save
      flash[:notice] = 'Deposit has been requested'
      if deposit.amount > deposit.from_wallet.balance
        deposit.reject!
      else
        deposit.accept!
        TransactionsWorker.perform_async(deposit.id)
      end
    else
      flash[:error] = 'Deposit request failed'
    end
    redirect_to root_path
  end

  private

  def deposit_params
    params.require(:deposit).permit(:from_wallet_id, :to_wallet_id, :amount)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.includes(:wallet).all.page params[:page]
  end

  def show
    @stock = Stock.includes(:wallet).find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.includes(:wallet).all.page params[:page]
  end

  def show
    @team = Team.includes(:users).find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:wallet).all.page params[:page]
  end

  def show
    @user = User.includes(:wallet).find(params[:id])
  end
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController

  def new
    @type = params[:type]
    id = params[:id]
    if @type == "user"
      @user = User.find(id)
      @wallet = @user.wallet
    elsif @type == "team"
      @team = Team.find(id)
      @wallet = @team.wallet
    else
      @stock = Stock.find(id)
      @wallet = @stock.wallet
    end
    @wallets = Wallet.all
    @withdraw = Withdraw.new
  end

  def create
    withdraw = Withdraw.new(withdraw_params)
    if withdraw.save
      flash[:notice] = 'Withdraw has been requested'
      if withdraw.amount > withdraw.from_wallet.balance
        withdraw.reject!
      else
        withdraw.accept!
        TransactionsWorker.perform_async(withdraw.id)
      end
    else
      flash[:error] = 'Withdraw request failed'
    end
    redirect_to root_path
  end

  private

  def withdraw_params
    params.require(:withdraw).permit(:from_wallet_id, :to_wallet_id, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/deposits/new.html.erb
<div class="result-container">
  <div class="result">
    <%= form_for @deposit do |f| %>

      <div>
        <%= f.label "Source Wallet" %>
        <%= f.select "from_wallet_id", options_from_collection_for_select(@wallets, "id", "id") %>
        -->
        <%= f.label "#{@type}'s Wallet_id: #{@wallet.id}" %> 
        <%= f.hidden_field "to_wallet_id", value: @wallet.id %>
      </div>
      <div>
        <%= f.label "Amount" %>
        <%= f.text_field "amount" %>
      <div>
        <%= f.submit 'Deposit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="result-container">
  <div class="result">
    <div class="table">
      <table class="pretty">
        <tr>
          <th>Company Code</th>
          <th>Shares Count</th>
          <th>Walled ID</th>
          <th>Balance</th>
          <th>Actions</th>
        </tr>
        <% @stocks.each do |s| %>
          <tr>
            <td><%= s.company_code %></td>
            <td><%= s.share_counts %></td>
            <td><%= s.wallet.id %></td>
            <td><%= s.wallet.balance %></td>
            <td><%= link_to "View", s %>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="paginate">
      <%= paginate @stocks %>
    </div>

  </div>
</div>

app/views/stocks/show.html.erb
<div class="result-container">
  <div class="result">
    <div class="table">
      <table class="bigger">
        <tr>
          <td><b>Company Code</b> </td>
          <td><%= @stock.company_code %></td>
        </tr>
        <tr>
          <td><b>No of shares</b></td>
          <td><%= @stock.share_counts %></td>
        </tr>
        <tr>
          <td><%= link_to "Deposit", new_deposit_path(type: "stock", id: @stock) %></td>
          <td><%= link_to "Withdraw", new_withdraw_path(type: "stock", id: @stock) %></td>
        </tr>
      </table>
    </div>
  </td>
</td>

app/views/users/index.html.erb
<div class="result-container">
  <div class="result">
    <div class="table">
      <table class="pretty">
        <tr>
          <th>First Name </th>
          <th>Last Name</th>
          <th>Date of Birth</th>
          <th>Teams Joined</th>
          <th>Walled ID</th>
          <th>Balance</th>
          <th>Actions</th>
        </tr>
        <% @users.each do |u| %>
          <tr>
            <td><%= u.first_name %></td>
            <td><%= u.last_name %></td>
            <td><%= u.dob %></td>
            <td><%= u.teams.count %></td>
            <td><%= u.wallet.id %></td>
            <td><%= u.wallet.balance %></td>
            <td><%= link_to "View", u %>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="paginate">
      <%= paginate @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="result-container">
  <div class="result">
    <div class="table">
      <table class="bigger">
        <tr>
          <td><b>First Name <b></td>
          <td><%= @user.first_name %></td>
        </tr>
        <tr>
          <td><b>Last Name<b></td>
          <td><%= @user.last_name %></td>
        </tr>
        <tr>
          <td><b>Date of Birth<b></td>
          <td><%= @user.dob %></td>
        </tr>
        <tr>
          <td><%= link_to "Deposit", new_deposit_path(type: "user", id: @user) %></td>
          <td><%= link_to "Withdraw", new_withdraw_path(type: "user", id: @user) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/withdraws/new.html.erb
<div class="result-container">
  <div class="result">
    <%= form_for @withdraw do |f| %>

      <div>
        <%= f.label "#{@type}'s Wallet_id: #{@wallet.id}" %> 
        <%= f.hidden_field "from_wallet_id", value: @wallet.id %>
        -->
        <%= f.label "Destination Wallet" %>
        <%= f.select "to_wallet_id", options_from_collection_for_select(@wallets, "id", "id") %>
      </div>
      <div>
        <%= f.label "Amount" %>
        <%= f.text_field "amount" %>
      <div>
        <%= f.submit 'Withdraw' %>
      </div>
    <% end %>
  </div>
</div>